version: '3.8'
services:
  # Using MongoDB with HTTP interface since DocumentDB is MongoDB-compatible
  mongodb:
    image: mongo:7.0
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testuser
      - MONGO_INITDB_ROOT_PASSWORD=testpass
      - MONGO_INITDB_DATABASE=test_db
    volumes:
      - mongodb-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s

  # DocumentDB HTTP API Gateway (simulates DocumentDB REST API)
  documentdb-api:
    image: python:3.11-slim
    depends_on:
      mongodb:
        condition: service_healthy
    ports:
      - "0.0.0.0:10260:10260"
    volumes:
      - ./api-server.py:/app/api-server.py:ro
    working_dir: /app
    command: >
      sh -c "
        pip install flask pymongo &&
        python api-server.py
      "
    environment:
      - MONGODB_URI=mongodb://testuser:testpass@mongodb:27017/test_db?authSource=admin

volumes:
  mongodb-data:
    driver: local

networks:
  default:
    name: documentdb-network